### ISSUE TITLE
Add toggle to settings to add open / close indicator to the warning container.

### ISSUE THREAD

**Issue by liamegan** [fxhash/fxhash-website#273]

**Comment by ciphrd** [comment]
I'm not sure to understand you you mean with "warning container"

**Comment by liamegan** [comment]
This guy:
![image](https://user-images.githubusercontent.com/627944/181305535-8ddac229-02fd-4abc-81de-76832fb0bd79.png)

It has a classname of `Warning_message`, so I assumed nomenclature :)

**Comment by GemN** [comment]
I think the announcement should not be configurable, the flow at the moment is:
- First time you get to the page, the announcement is open, on the browser.
- You close it, the announcement stay hidden until there is a different message. 

Like settings, it's recorded in the browser localStorage the visibility of the announcement message so if you open another browser or go in private navigation you'll see the announcement, no matters if we add a special setting "open / close" or not.

I don't think we want users to miss on important announcements since it allows to reach people not on discord / have mails lost in the inbox hell

**Comment by liamegan** [comment]
Understood. Closing.
