### ISSUE TITLE
[Article editor] Fix lists conversion to markdown (creates multiline)

### ISSUE THREAD

**Issue by ciphrd** [fxhash/fxhash-website#281]
* PR target: `feature/articles`

Steps to reproduce:
* create article
* add a list
* add a few points
* wait for save
* reload:

![image](https://user-images.githubusercontent.com/18054507/181222254-852782ba-50a8-4be0-b610-3d521ca5af1d.png)

It appears that the bug occurs at the slate to markdown conversion, this is an output of the markdown locally saved:
![image](https://user-images.githubusercontent.com/18054507/181222422-143cae9a-da01-49d9-8276-4cfe78f1fa62.png)

However, it could also be an issue at the edition stage (pressing enter could ne the cuase, needs investigation)

As you can see, it adds an empty line between each bullet, which tricks slate into create multiple lists inside paragraphs.

- [ ] fix the conversion issue (no empty line between list points)
- [ ] add normalization rule so that <ul> elements must be at the root

**Comment by maerzhase** [comment]
So i think the editing is all correct. We end up with a clean structure of 
```js
{
  type: 'list',
  children: [{
    type: 'listItem',
    children: [{
      text: 'test'
    }]
  }]
}
```

But markdown / GFM parses the texts of listItems with an additional paragraph around the text—hence the additional line + menu because it renders a paragraph inside the list item. This screenshot shows how github itself parses the markdown of lists:

<img width="1257" alt="Screenshot 2022-07-28 at 08 41 18" src="https://user-images.githubusercontent.com/1128485/181438774-b7625621-76d2-44f8-8c06-102e421877b2.png">

As I mentioned in discord. We could use slate normalisation and would be pretty easy to do like so:

```js
  if(node.type === 'list') {
      for (const [child, childPath] of Node.children(editor, path)) {
        if (child.type === "listItem") {
	  if (child.children) {
            Transforms.unwrapNodes(editor, {
	      at: [...childPath, 0]
            })
	  }
        }
      } 
    }
```

But the problem with that is: 
- a. Currently we dont normalise on init, its only done on edit
- b. The static remark parser output would not match the editable slate output 

So I think we either have to adjust how the markdown parser parses list + listItem nodes. Or we have to render a different paragraph inside listItem.
