### ISSUE TITLE
[Articles] Add articles mentioning a project / gentk on their page 

### ISSUE THREAD

**Issue by ciphrd** [fxhash/fxhash-website#297]
* base branch `feature/articles`

Add the list of articles mentioning a project on the project page (same for single tokens)

**Comment by Anaglyph-ic** [comment]
- adding these in the article metadata as JSON arrays would be nice (I guess that's how you'll do it, but this could also be doable server-side so I guess it doesn't hurt asking)
- adding contract + tokenId for each (instead of only adding/using fxhash API slug + iteration and/or fxhash API ID) would be helpful to reusers.

**Comment by ciphrd** [comment]
This is done at the backend-level.
The markdown itself and the `tezos-storage-pointer` directive does this already, some processing at the backend level is required to process this and link it, I don't think it should be inserted into the json metadata (it would be redundant).
