### ISSUE TITLE
/objkt route

### ISSUE THREAD

**Issue by crzypatchwork** [fxhash/fxhash-website#9]
As it's known the hicetnunc marketplace uses the /objkt route to redirect users for viewing tokens which are part of it's collection. Why fxhash started using the same keyword/route? Doesn't this cause confusion/misinformation/devalues the original objkt collection? Was hicetnunc marketplace consulted about such matter?

**Comment by ciphrd** [comment]
If you are interested in the full story...

When I started to work on fxhash, I was quite new to this space (about 1 month old). I didn't know much about the Tezos ecosystem, and I only knew H=N, objkt.com and few other actors.
Because "OBJKT" was everywhere (ie. on the 2 platforms I was on at the time being, which were not affiliated) I naively thought that "OBJKT" was the actual nomenclature to describe FA2 tokens.

I learnt during the development that OBJKT was only referring to the H=N tokens, but "objkt" was already over the whole codebase and I decided to fix it later on... well it's never really been fixed x)

It will have to be fixed, but it isn't really a priority given everything else there is to do.

Thankfully I was able to learn about it before I released the contracts, and set a different symbol in the contracts.

**Comment by ciphrd** [comment]
c4d40165647a0125fe7b37b36fc6494bfcf7ae44

**Comment by ciphrd** [comment]
Well it was quite easy to fix

**Comment by crzypatchwork** [comment]
ty for the fix
